-- Generated by Omagen. Window style: border=solid border_size=0 shape=rounded spacing=compact depth=flat inactive=native.
local active_border_color = "rgb(005286)"
local inactive_border_color = "rgb(393e43)"

hl.config({
  general = {
    col = { active_border = active_border_color, inactive_border = inactive_border_color },
    gaps_in = 4, gaps_out = 5,
  },
  group = { col = { border_active = active_border_color, border_inactive = inactive_border_color }, },
  decoration = {
    rounding = 8, rounding_power = 3,
    shadow = { enabled = false },
  },
})
